<a href="https://colab.research.google.com/github/anaisrcast/Data-Science-Practice/blob/main/SalesData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
print("Import Complete")

Import Complete

In [34]:
sales_df = pd.read_csv("messy_ecommerce_sales_data.csv")
sales_df.head(5)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [42]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1   Customer_Name   103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      102 non-null    datetime64[ns]
 4   Product         103 non-null    object
 5   Category        95 non-null     object
 6   Quantity        98 non-null     object
 7   Price           98 non-null     object
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(8)
memory usage: 9.0+ KB

In [49]:
#strip the column headers
sales_df.columns = sales_df.columns.str.strip()

#Correct data types
#------------
#Date
sales_df['Order_Date'] = pd.to_datetime(sales_df['Order_Date'], format='mixed',errors='coerce')
#Float Price
sales_df['Price'] = pd.to_numeric(sales_df['Price'], errors = "coerce")
#Interger Quantity
sales_df['Quantity'] = pd.to_numeric(sales_df['Quantity'], errors = "coerce")

#+ rows with make them all the same case
if sales_df['Category'].dtype == 'object':
    sales_df['Category'] = sales_df['Category'].str.lower()

In [50]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1   Customer_Name   103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      102 non-null    datetime64[ns]
 4   Product         103 non-null    object
 5   Category        95 non-null     object
 6   Quantity        97 non-null     float64
 7   Price           94 non-null     float64
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 9.0+ KB

In [23]:
sales_df[sales_df['Category'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
33,133,Customer_133,ORD-68182,12/5/2024,Biography,NaN,5,343.24,Credit Card,Shipped,1716.20
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,NaN,1,696.71,Credit Card,Delivered,696.71
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,NaN,2,418.38,Credit Card,Processing,836.76
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.48
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,NaN,4,538.35,PayPal,Processing,2153.40
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.76
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.02

# **TRY** to creat a dimension table for the different 'product'

Will use this to fill in the nulls within the original dataset

In [56]:
prod_cat_df = sales_df[['Product', 'Category']].dropna()
prod_cat_df = prod_cat_df.drop_duplicates()
prod_cat_df.sort_values(['Product', 'Category']).head(20)

       Product     Category
46  Basketball   electronic
10  Basketball       sports
4    Biography        books
17     Blender   electronic
0      Blender         home
11      Comics        books
13     Fiction        books
44    Football       sports
75  Headphones  electronics
47      Jacket     clothing
56       Jeans     clothing
28        Lamp  electronics
31        Lamp         home
45      Laptop  electronics
74   Microwave  electronics
16   Microwave         home
3      Science        books
12       Shoes     clothing
1   Smartphone  electronics
35  Smartwatch  electronics

In [14]:
sales_df['Product'].unique()

array(['Blender', 'Smartphone', 'Tennis Racket', 'Science', 'Biography',
       'Basketball', 'Comics', 'Shoes', 'Fiction', 'Microwave',
       'Yoga Mat', 'Vacuum', 'Lamp', 'T-shirt', 'Smartwatch',
       'Headphones', 'Football', 'Laptop', 'Jacket', 'shoes', 'Jeans'],
      dtype=object)